//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Library.DAL
{
    using System.Data.Entity;

    public partial class ELibraryEntities : DbContext
    {
        public ELibraryEntities()
            : base("name=ELibraryEntities")
        {
        }


        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Author> Authors { get; set; }
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<BookAuthorMapping> BookAuthorMappings { get; set; }
    }
}
